version: '3'

services:
  rest-api:
    image: tical1621-local/rest-api

    build:
      context: .

    ports:
      - '8100:8000'

    environment:
      DB_HOST: "postgresql"
      REDIS_HOST: "redis://redis:6379"

  celery-beat:
    image: tical1621-local/rest-api

    command: ["celery", "-A", "DjangoApi", "beat", "-l", "info"]

    environment:
      REDIS_HOST: "redis://redis:6379"

  celery-worker:
    image: tical1621-local/rest-api

    command: ["celery", "-A", "DjangoApi", "worker", "-l", "info"]


    environment:
        DB_HOST: "postgresql"
        REDIS_HOST: "redis://redis:6379"

  postgresql:
    image: postgres:14-alpine

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "0000"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_DB: "mytestdb"

  redis:
    image: redis:6.2-alpine
#    ports:
#      - "6379:6379"

volumes:
  postgres-data:
