version: '3'

services:
  rest-api:
    image: tical1621-local/rest-api

    build:
      context: .

    ports:
      - '8100:8000'

# TODO: Configure DB & Redis connections via env
    environment:
      DB_HOST: "postgresql"  # PostgreSQL container will be accessible on network via name of the service
      REDIS_HOST: "redis://redis:6379"  # Same for Redis

  celery-beat:
    image: tical1621-local/celery-beat

    command: ["celery", "beat", "-A", "DjangoApi", "-l", "info"]

# TODO: Configure Redis connection via env
    environment:
      REDIS_HOST: "redis://redis:6379"

  celery-worker:
    image: tical1621-local/celery-worker

    command: ["celery", "worker", "-A", "DjangoApi", "-l", "info"]

# TODO: Configure DB & Redis connections via env
    environment:
        DB_HOST: postgresql
        REDIS_HOST: "redis://redis:6379"

  postgresql:
    image: postgres:14-alpine

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "0000"

  redis:
    image: redis:6.2-alpine
#    ports:
#      - "6379:6379"

volumes:
  postgres-data:
